project_id = "eywvzwdctkmgxfsmlqkb"

[functions.stream-proxy]
verify_jwt = false

[functions.parse-playlist]
verify_jwt = false

[functions.get-series-info]
verify_jwt = false

[functions.log-event]
verify_jwt = false

[functions.parse-epg]
verify_jwt = false